# Generated by Django 3.2.16 on 2025-10-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryRoleAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150, unique=True)),
                ('summary', models.JSONField()),
                ('insights', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['role'],
            },
        ),
    ]
