# Generated by Django 3.2.16 on 2025-10-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('role', models.CharField(db_index=True, max_length=150)),
                ('level', models.CharField(db_index=True, max_length=100)),
                ('location', models.CharField(db_index=True, max_length=150)),
                ('state', models.CharField(db_index=True, max_length=30)),
                ('country', models.CharField(db_index=True, max_length=100)),
                ('currency', models.CharField(db_index=True, max_length=10)),
                ('work_model', models.CharField(db_index=True, max_length=50)),
                ('base_salary_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('base_salary_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_compensation', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observed_at', models.DateField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['role', 'level', 'state', 'work_model'],
            },
        ),
        migrations.AddIndex(
            model_name='salaryobservation',
            index=models.Index(fields=['role', 'country', 'state', 'work_model'], name='testapp_sal_role_99d6c6_idx'),
        ),
        migrations.AddIndex(
            model_name='salaryobservation',
            index=models.Index(fields=['role', 'level', 'currency'], name='testapp_sal_role_9dee61_idx'),
        ),
        migrations.AddConstraint(
            model_name='salaryobservation',
            constraint=models.UniqueConstraint(fields=('source', 'role', 'level', 'location', 'state', 'country', 'currency', 'work_model', 'base_salary_min', 'base_salary_max', 'total_compensation', 'observed_at'), name='unique_salary_observation'),
        ),
    ]
